### ISSUE TITLE
where to set community string and port?

### ISSUE THREAD

**Issue by doctore74** [Graylog2/graylog-plugin-snmp#11]
Hi, great work!

But how/where is it possible to set the community string or the port for the trap daemon?

I'm using Graylog v1.3.4 on CentOS 7.

Thanks for the help.

Regards
Chris

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
