### ISSUE TITLE
Plugin fails when changing port to 162 ?

### ISSUE THREAD

**Issue by irom77** [Graylog2/graylog-plugin-snmp#12]
I prefer plugin to listen on port 162 but when I change it fails . Is it possible plugin to listen on port 162 instead of 1620 ?

**Comment by joschi** [comment]
@irom77 Port 162 is a so-called privileged port which only the superuser (i. e. "root") is allowed to bind to.

There are various ways to work around this without running Graylog as root user (which is strongly discouraged), please see https://debian-administration.org/article/386/Running_network_services_as_a_non-root_user. for some suggestions.
For Graylog, using `authbind` would be the most simple way to allow binding to privileged ports (see https://github.com/Graylog2/fpm-recipes/blob/2.0/recipes/graylog-server/files/environment#L10-L12).

**Comment by irom77** [comment]
Great, thnx !
