### ISSUE TITLE
Is there any way possible that one can run the plug-in using native UDP 162?

### ISSUE THREAD

**Issue by bubba198** [Graylog2/graylog-plugin-snmp#16]
Hi everyone,

Is there any way possible that one can run the plug-in using native UDP 162?

Trial and error reveals that the answer is NO but I am wondering whether someone has come up with a remedy to this issue?

Thanks

**Comment by joschi** [comment]
@bubba198 Ports below 1024 are so-called privileged ports which only the superuser (root) can bind to.

You'll need to either bind to a high port >1024 and use a packet filter such as Netfilter/IPTables to redirect traffic from 162/udp to that high port, or you can use a program like `authbind` to enable the Java process to bind to privileged ports.

See https://github.com/Graylog2/documentation/issues/213 for related information.

In general, we are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
