### ISSUE TITLE
no OID shown

### ISSUE THREAD

**Issue by kemijoki** [Graylog2/graylog-plugin-snmp#8]
Hi,

I am using graylog 1.3.2 and graylog-plugin-snmp version 0.3.0. Using the mentioned test command

snmptrap -v 2c -c public 127.0.0.1:162 '' .1.3.6.1.4.1.5089.1.0.1 .1.3.6.1.4.1.5089.2.0.999 s "123456"

An entry in graylog can be found however, no OID is shown, I would expect to see at least a couple of numbers if the corresponding MIBs could not be loaded?

These are the only information I get:

Received by
    snmptraps on  49e92dd5 / graylog
Stored in index
    graylog2_0
gl2_remote_ip
    127.0.0.1
gl2_remote_port
    41703
message
    SNMP trap 1589655778
snmp_frxDownloadTrap
    791579157915
snmp_request_id
    1589655778
snmp_trap_type
    TRAP
source
127.0.0.1

Any ideas how to solve this? (I would like to receive traps from a cisco device but there are the same problems...

Kind regards,
Mira

**Comment by mariussturm** [comment]
Closing this, please ping us again if the problem still exist.
